package by.popolamov.restourant.controller.command;

/**
 * The enum CommandType.
 */
public enum CommandType {
    //COMMON
    SIGN_IN, SIGN_OUT, SIGN_UP,
    MOVE_TO_LOGIN_PAGE, MOVE_TO_MAIN_PAGE, MOVE_TO_SIGNUP_PAGE,
    CHANGE_LOCALE,

    //USER
    MOVE_TO_CART_PAGE, ADD_DISH_TO_CART, COMPLETE_CART,
    CART_REDIRECT_PAGE, ORDER_REDIRECT_PAGE,
    MOVE_TO_ACCOUNT_PAGE,
    //ADMIN
    GET_USERS, CHANGE_USER_ROLE, CHANGE_USER_STATUS,
    MOVE_TO_ORDERS_PAGE, COMPLETE_ORDER, DELETE_ORDER,

    ADD_MENU,

    DEFAULT
}
